### ISSUE TITLE
Use of apostrophes in test

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/erb-templating#11]
User: Gabi O'Connor

Batch: web-0715

Current Lesson: An Introduction to ERB

Location: https://learn.co/tracks/web-development-with-ruby-on-rails-2015/erb/displaying-data/an-introduction-to-erb?track_id=9683&batch_id=81

Bug Description: Hi, in the 'Introduction to ERB' lab, for the #make_index! test, the test expects the movie url to include apostrophes, even though urls should not include apostrophes. Example: the test expects the Pan's Labyrinth link to equal: <li><a href=\"movies/pan's_labyrinth.html\">Pan's Labyrinth</a></li> ...instead of <li><a href=\"movies/pans_labyrinth.html\">Pan's Labyrinth</a></li>

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by jmburges** [comment]
This issue is bringing up a concept of URL encoding/decoding. Only standard characters should be used in URLs and in this lab we allow things like apostrophe's which should either be removed, or better yet! converted appropriratly to their URL encoded counterpart. For example `'` turns into `%27`. This lab should include that concept in the instructtions, maybe a point to [this](http://ruby-doc.org/stdlib-2.1.1/libdoc/uri/rdoc/URI/Escape.html) as how to do it, and a test that ensures that they actually do it!
